### PR TITLE
Support different database dialects

### PR DESCRIPTION
**Pull request by seth2810**

### CODE REVIEW

**Comment by seth2810** [comment]
@martinohmann Hey! Please look at this.

**Comment by martinohmann** [comment]
@seth2810 thanks for the PR. I did not have the time yet to look into it deeply, but in general this looks like a useful change. Will review it closely tomorrow :).

**Comment by seth2810** [comment]
Cool! Thanks.

**Review by martinohmann — APPROVED** [review]
Looks good to me.

**Comment by martinohmann** [comment]
@seth2810 I tagged your feature with `v0.1.0`, thanks for the contribution!

**Pull request merged**
